#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only)

if [ -n "$STAGED_FILES" ]; then
  echo "Formatting staged files..."
  echo "$STAGED_FILES" | xargs prettier --write
  echo "$STAGED_FILES" | xargs eslint --fix
fi

echo "$STAGED_FILES" | xargs git add